// Maps each question ID to the trait it primarily measures, its weight, and
// validation group (used to detect contradictory answer patterns).
// Q 47–49 are social-desirability checks — they have no trait and are excluded
// from normal trait scoring.
export const QUESTION_MAPPING = [
  { questionId:  1, trait: 'Social',        subTrait: 'Initiative',       weight: 4, reverseScored: false, validationGroup: 'B' },
  { questionId:  2, trait: 'Social',        subTrait: 'Energy',           weight: 3, reverseScored: false, validationGroup: 'B' },
  { questionId:  3, trait: 'Leadership',    subTrait: 'Volunteerism',     weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId:  4, trait: 'Empathy',       subTrait: 'Patience',         weight: 4, reverseScored: false, validationGroup: 'C' },
  { questionId:  5, trait: 'Empathy',       subTrait: 'Tolerance',        weight: 3, reverseScored: true,  validationGroup: 'C' },
  { questionId:  6, trait: 'Discipline',    subTrait: 'Study Habits',     weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId:  7, trait: 'Discipline',    subTrait: 'Goal Consistency', weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId:  8, trait: 'Discipline',    subTrait: 'Preparedness',     weight: 3, reverseScored: false, validationGroup: 'A' },
  { questionId:  9, trait: 'Introspection', subTrait: 'Stress Response',  weight: 4, reverseScored: false, validationGroup: 'F' },
  { questionId: 10, trait: 'Introspection', subTrait: 'Confidence',       weight: 3, reverseScored: false, validationGroup: 'F' },
  { questionId: 11, trait: 'Introspection', subTrait: 'Resilience',       weight: 4, reverseScored: false, validationGroup: 'F' },
  { questionId: 12, trait: 'Creativity',    subTrait: 'Exploration',      weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 13, trait: 'Creativity',    subTrait: 'Curiosity',        weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 14, trait: 'Creativity',    subTrait: 'Non-Conformity',   weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 15, trait: 'Creativity',    subTrait: 'Growth Mindset',   weight: 4, reverseScored: false, validationGroup: 'D' },
  { questionId: 16, trait: 'Introspection', subTrait: 'Self-Concept',     weight: 3, reverseScored: false, validationGroup: 'F' },
  { questionId: 17, trait: 'Creativity',    subTrait: 'Tech Openness',    weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 18, trait: 'Leadership',    subTrait: 'Initiative',       weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId: 19, trait: 'Empathy',       subTrait: 'Conflict Resolve', weight: 4, reverseScored: false, validationGroup: 'C' },
  { questionId: 20, trait: 'Empathy',       subTrait: 'Collaboration',    weight: 4, reverseScored: false, validationGroup: 'C' },
  { questionId: 21, trait: 'Empathy',       subTrait: 'Generosity',       weight: 4, reverseScored: false, validationGroup: 'C' },
  { questionId: 22, trait: 'Discipline',    subTrait: 'Integrity',        weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId: 23, trait: 'Introspection', subTrait: 'Bounce-back',      weight: 4, reverseScored: false, validationGroup: 'F' },
  { questionId: 24, trait: 'Discipline',    subTrait: 'Persistence',      weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId: 25, trait: 'Introspection', subTrait: 'Emotional Depth',  weight: 3, reverseScored: false, validationGroup: 'F' },
  { questionId: 26, trait: 'Empathy',       subTrait: 'EQ Awareness',     weight: 4, reverseScored: false, validationGroup: 'C' },
  { questionId: 27, trait: 'Leadership',    subTrait: 'Communication',    weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId: 28, trait: 'Introspection', subTrait: 'Adaptability',     weight: 3, reverseScored: false, validationGroup: 'F' },
  { questionId: 29, trait: 'Creativity',    subTrait: 'Tech Adoption',    weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 30, trait: 'Creativity',    subTrait: 'Problem Seeking',  weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 31, trait: 'Empathy',       subTrait: 'Mentoring',        weight: 3, reverseScored: false, validationGroup: 'C' },
  { questionId: 32, trait: 'Risk',          subTrait: 'Ambition',         weight: 4, reverseScored: false, validationGroup: 'E' },
  { questionId: 33, trait: 'Risk',          subTrait: 'Entrepreneurship', weight: 4, reverseScored: false, validationGroup: 'E' },
  { questionId: 34, trait: 'Risk',          subTrait: 'Risk Tolerance',   weight: 4, reverseScored: false, validationGroup: 'E' },
  { questionId: 35, trait: 'Discipline',    subTrait: 'Accountability',   weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId: 36, trait: 'Leadership',    subTrait: 'Process Improve',  weight: 3, reverseScored: false, validationGroup: 'A' },
  { questionId: 37, trait: 'Creativity',    subTrait: 'Future Thinking',  weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 38, trait: 'Introspection', subTrait: 'Values Clarity',   weight: 3, reverseScored: false, validationGroup: 'F' },
  { questionId: 39, trait: 'Introspection', subTrait: 'Motivation',       weight: 3, reverseScored: false, validationGroup: 'F' },
  { questionId: 40, trait: 'Discipline',    subTrait: 'Analytical Think', weight: 4, reverseScored: false, validationGroup: 'A' },
  { questionId: 41, trait: 'Risk',          subTrait: 'Uncertainty Mgmt', weight: 4, reverseScored: false, validationGroup: 'E' },
  { questionId: 42, trait: 'Creativity',    subTrait: 'Adaptability',     weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 43, trait: 'Introspection', subTrait: 'Future Belief',    weight: 3, reverseScored: false, validationGroup: 'F' },
  { questionId: 44, trait: 'Social',        subTrait: 'Openness',         weight: 3, reverseScored: false, validationGroup: 'B' },
  { questionId: 45, trait: 'Creativity',    subTrait: 'Learning Drive',   weight: 3, reverseScored: false, validationGroup: 'D' },
  { questionId: 46, trait: 'Discipline',    subTrait: 'Task Completion',  weight: 3, reverseScored: false, validationGroup: 'A' },
  // Social-desirability checks — excluded from trait scoring
  { questionId: 47, trait: null, subTrait: 'SocialDesirability', weight: 0, reverseScored: false, validationGroup: 'SD' },
  { questionId: 48, trait: null, subTrait: 'SocialDesirability', weight: 0, reverseScored: false, validationGroup: 'SD' },
  { questionId: 49, trait: null, subTrait: 'SocialDesirability', weight: 0, reverseScored: false, validationGroup: 'SD' },
];

export const getQuestionMeta = (questionId) =>
  QUESTION_MAPPING.find((q) => q.questionId === questionId) || null;
