export const ARCHETYPES = [
  {
    id: 'founder',
    emoji: '🚀',
    name: 'Future Founder',
    gradient: 'from-[#3A0CA3] to-[#FF4D6D]',
    blurb: 'You see problems as puzzles waiting for your solution. Bold moves come naturally to you.',
    traits: ['Visionary', 'Decisive', 'Risk-taker'],
  },
  {
    id: 'creative',
    emoji: '🎨',
    name: 'Creative Soul',
    gradient: 'from-[#FF4D6D] to-[#FFC868]',
    blurb: 'Your mind paints in colors others can\'t see yet. Expression is how you make sense of the world.',
    traits: ['Imaginative', 'Expressive', 'Original'],
  },
  {
    id: 'butterfly',
    emoji: '🦋',
    name: 'Social Butterfly',
    gradient: 'from-[#22D3C5] to-[#3A0CA3]',
    blurb: 'Rooms light up when you walk in. Connection is your superpower and your fuel.',
    traits: ['Charismatic', 'Warm', 'Energizing'],
  },
  {
    id: 'thinker',
    emoji: '🧠',
    name: 'Deep Thinker',
    gradient: 'from-[#3A0CA3] to-[#22D3C5]',
    blurb: 'You go three layers deeper than everyone else in the conversation — and you like it there.',
    traits: ['Analytical', 'Curious', 'Reflective'],
  },
  {
    id: 'chaos',
    emoji: '⚡',
    name: 'Chaos Creator',
    gradient: 'from-[#FFC868] to-[#FF4D6D]',
    blurb: 'Predictable is boring. You thrive on spontaneity and turning plans upside down — for the better.',
    traits: ['Spontaneous', 'Bold', 'Unfiltered'],
  },
  {
    id: 'growth',
    emoji: '🌱',
    name: 'Growth Seeker',
    gradient: 'from-[#22D3C5] to-[#FFC868]',
    blurb: 'Yesterday\'s you is basically a stranger. You\'re always one rep, one page, one habit further.',
    traits: ['Driven', 'Adaptive', 'Hungry'],
  },
  {
    id: 'visionbuilder',
    emoji: '🏆',
    name: 'Vision Builder',
    gradient: 'from-[#3A0CA3] to-[#FFC868]',
    blurb: 'You don\'t just dream big — you sketch the blueprint and start laying bricks immediately.',
    traits: ['Strategic', 'Patient', 'Ambitious'],
  },
  {
    id: 'communityleader',
    emoji: '💜',
    name: 'Community Leader',
    gradient: 'from-[#FF4D6D] to-[#3A0CA3]',
    blurb: 'People naturally orbit you. You build the spaces where everyone feels like they belong.',
    traits: ['Empathetic', 'Inclusive', 'Trusted'],
  },
];

export const getArchetype = (id) => ARCHETYPES.find((a) => a.id === id) || ARCHETYPES[0];
